
title: Mahidul Haque #Your awesome title
email: mahikysr@gmail.com
description: > # this means to ignore newlines until "baseurl"
  A platform where I write insightful tech blogs, share my explored knowledge, and publish my solved CTF writeups.
  It also features my projects, both ongoing and completed, showcasing my skills and interests in cybersecurity and technology.

baseurl: # the subpath of the site
url: https://mahidulhq.github.io # the base hostname & protocol for your site

permalink: /:2025-:October/:Mahidul
timezone: Asia/Dhaka

favicon: /assets/img/favicon.ico

google_analytics: #UA—XXXXXXXX-X
disqus_shortname: #disqus shortname
cusdis:
    app_id: #your cusdis app_id

user:
  name: Mahidul Haque
  pic: /assets/img/profile.jpg
  picAlt: "mahidulhq"
  job: Cybersecurity Enthusiast | UX/UI Designer & Figma Expert
  aboutme: true # comment this out if you don't need the 'about' page.

exclude:
  - README.md
  - LICENSE
  - github

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comment: true   

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown 

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false
